gtkwave::addSignalsFromList "tb_cpu.uut.clk"
gtkwave::addSignalsFromList "tb_cpu.uut.PC"
gtkwave::addSignalsFromList "tb_cpu.uut.IF_ID_Instr"
gtkwave::addSignalsFromList "tb_cpu.uut.regs[1]"
gtkwave::addSignalsFromList "tb_cpu.uut.regs[2]"
gtkwave::addSignalsFromList "tb_cpu.uut.regs[3]"
gtkwave::addSignalsFromList "tb_cpu.uut.regs[4]"
gtkwave::addSignalsFromList "tb_cpu.uut.regs[5]"
gtkwave::addSignalsFromList "tb_cpu.uut.EX_MEM_ALUResult"
gtkwave::setZoomRange 0 320000
gtkwave::setDataFormat "tb_cpu.uut.IF_ID_Instr" "Hex"
gtkwave::setDataFormat "tb_cpu.uut.regs[1]" "Decimal"
gtkwave::setDataFormat "tb_cpu.uut.regs[2]" "Decimal"
gtkwave::setDataFormat "tb_cpu.uut.regs[3]" "Decimal"
gtkwave::setDataFormat "tb_cpu.uut.regs[4]" "Decimal"
gtkwave::setDataFormat "tb_cpu.uut.regs[5]" "Decimal"
